# Change these first
owner: ChrAlpha # Your GitHub username
repo: upptimes # Your Github repository name

# Add your sites here
sites:
  - name: Blog
    url: https://blog.ichr.me
  - name: Theme Cards Site
    url: https://theme-cards.ichr.me
  - name: Personal Homepage
    url: https://ichr.me

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ichr.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.jsdelivr.net/npm/ckx@0.0.1/favicon/favicon.ico
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status of my sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ChrAlpha

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
